/* ============================================================
   FrontlineWire — app.js
   Loads stories from data.json (generated by update.py)
   and renders the site dynamically.
   ============================================================ */

// --- DATE & TIME ---
function formatDate(d) {
  return d.toLocaleDateString('en-US', { weekday:'long', year:'numeric', month:'long', day:'numeric' });
}

document.getElementById('current-date').textContent = formatDate(new Date());
document.getElementById('footer-year').textContent = new Date().getFullYear();

// --- CONFLICT TRACKER DATA ---
// This is the static list of tracked conflicts.
// Severity is updated manually or via update.py if you add that feature.
const TRACKED_CONFLICTS = [
  { name: 'Iran / Israel', region: 'middle-east', severity: 'high', status: 'Critical' },
  { name: 'Ukraine',       region: 'europe',      severity: 'high', status: 'Active'   },
  { name: 'Sudan',         region: 'africa',       severity: 'high', status: 'Active'   },
  { name: 'Gaza',          region: 'middle-east', severity: 'high', status: 'Active'   },
  { name: 'Myanmar',       region: 'asia',         severity: 'med',  status: 'Ongoing'  },
  { name: 'Haiti',         region: 'americas',     severity: 'med',  status: 'Ongoing'  },
  { name: 'DRC',           region: 'africa',       severity: 'med',  status: 'Ongoing'  },
  { name: 'Somalia',       region: 'africa',       severity: 'med',  status: 'Ongoing'  },
  { name: 'Yemen',         region: 'middle-east', severity: 'med',  status: 'Ongoing'  },
  { name: 'Syria',         region: 'middle-east', severity: 'low',  status: 'Simmering'},
  { name: 'Ethiopia',      region: 'africa',       severity: 'low',  status: 'Fragile'  },
  { name: 'Colombia',      region: 'americas',     severity: 'low',  status: 'Ongoing'  },
  { name: 'Pakistan LOC',  region: 'asia',         severity: 'low',  status: 'Tension'  },
  { name: 'Iraq',          region: 'middle-east', severity: 'low',  status: 'Simmering'},
];

function renderConflictTracker() {
  const el = document.getElementById('conflict-tracker');
  document.getElementById('conflict-count').textContent = TRACKED_CONFLICTS.length;
  el.innerHTML = TRACKED_CONFLICTS.map(c => `
    <div class="conflict-item">
      <div class="conflict-dot ${c.severity}"></div>
      <div class="conflict-name">${c.name}</div>
      <div class="conflict-status">${c.status}</div>
    </div>
  `).join('');
}

// --- LOAD STORIES FROM data.json ---
async function loadStories() {
  let stories = [];
  try {
    const res = await fetch('data.json?t=' + Date.now());
    const data = await res.json();
    stories = data.stories || [];
    if (data.last_updated) {
      const d = new Date(data.last_updated);
      document.getElementById('last-updated').textContent =
        d.toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit', timeZoneName: 'short' });
    }
  } catch(e) {
    console.warn('data.json not found, using placeholder content.');
    stories = getPlaceholderStories();
  }
  return stories;
}

// --- PLACEHOLDER STORIES (shown before first update.py run) ---
function getPlaceholderStories() {
  return [
    {
      title: "Site is live — first update running soon",
      summary: "FrontlineWire is now online. The automated update script will populate this page with real conflict news within the next few minutes. Refresh this page after running update.py for the first time.",
      region: "Global",
      region_key: "all",
      source: "FrontlineWire",
      url: "#",
      published: new Date().toISOString(),
      is_hero: true
    }
  ];
}

// --- RENDER HERO ---
function renderHero(story) {
  document.getElementById('hero-region').textContent = story.region.toUpperCase();
  document.getElementById('hero-title').textContent = story.title;
  document.getElementById('hero-summary').textContent = story.summary;
  document.getElementById('hero-source').textContent = story.source;
  document.getElementById('hero-time').textContent = timeAgo(story.published);
  const link = document.getElementById('hero-link');
  link.href = story.url || '#';
  if (!story.url || story.url === '#') link.style.display = 'none';
}

// --- RENDER SIDEBAR ---
function renderSidebar(stories) {
  const el = document.getElementById('sidebar-stories');
  el.innerHTML = stories.slice(0, 4).map(s => `
    <div class="story-card">
      <div class="region-tag">${s.region.toUpperCase()}</div>
      <h3>${s.title}</h3>
      <p>${s.summary.substring(0, 120)}...</p>
      <div class="meta">
        <span>${s.source}</span>
        <span>${timeAgo(s.published)}</span>
      </div>
      ${s.url && s.url !== '#' ? `<a class="read-more" href="${s.url}" target="_blank" rel="noopener">Read More &rarr;</a>` : ''}
    </div>
  `).join('');
}

// --- RENDER REGIONAL SECTIONS ---
const REGIONS = [
  { key: 'middle-east', label: 'Middle East' },
  { key: 'europe',      label: 'Europe' },
  { key: 'africa',      label: 'Africa' },
  { key: 'asia',        label: 'Asia' },
  { key: 'americas',    label: 'Americas' },
];

function renderRegions(stories) {
  const el = document.getElementById('region-sections');
  const html = REGIONS.map(r => {
    const regional = stories.filter(s => s.region_key === r.key).slice(0, 4);
    if (!regional.length) return '';
    return `
      <div class="region-section">
        <h4>${r.label}</h4>
        ${regional.map(s => `
          <div class="mini-story">
            <h5><a href="${s.url || '#'}" target="_blank" rel="noopener">${s.title}</a></h5>
            <div class="meta">
              <span>${s.source}</span>
              <span>${timeAgo(s.published)}</span>
            </div>
          </div>
        `).join('')}
      </div>
    `;
  }).join('');
  el.innerHTML = html;
}

// --- RENDER BREAKING TICKER ---
function renderTicker(stories) {
  const headlines = stories.slice(0, 8).map(s => s.title).join('  &mdash;&mdash;  ');
  document.getElementById('ticker-text').innerHTML = headlines;
}

// --- NAV FILTER ---
function initNav(allStories) {
  document.querySelectorAll('.nav a').forEach(link => {
    link.addEventListener('click', e => {
      e.preventDefault();
      document.querySelectorAll('.nav a').forEach(a => a.classList.remove('active'));
      link.classList.add('active');
      const region = link.dataset.region;
      const filtered = region === 'all'
        ? allStories
        : allStories.filter(s => s.region_key === region);
      if (!filtered.length) return;
      renderHero(filtered[0]);
      renderSidebar(filtered.slice(1));
    });
  });
}

// --- UTILITY: TIME AGO ---
function timeAgo(iso) {
  if (!iso) return '—';
  const diff = (Date.now() - new Date(iso).getTime()) / 1000;
  if (diff < 60)   return 'Just now';
  if (diff < 3600) return Math.floor(diff/60) + 'm ago';
  if (diff < 86400) return Math.floor(diff/3600) + 'h ago';
  return Math.floor(diff/86400) + 'd ago';
}

// --- INIT ---
(async function init() {
  renderConflictTracker();
  const stories = await loadStories();
  if (!stories.length) return;
  renderHero(stories[0]);
  renderSidebar(stories.slice(1, 5));
  renderRegions(stories);
  renderTicker(stories);
  initNav(stories);
})();
